Use env. variable GLUSTER_BLOCK_ENABLED to enable/disable gluster-block-service
gluster/gluster-containers pull request #122
Opened 2019-01-15 10:37 UTC by nixpanic

Enable gluster-block services if `GLUSTER_BLOCK_ENABLED` is `"1"` and disable otherwise.

By default, `GLUSTER_BLOCK_ENABLED` is set as `"1"`.

This change was recently reverted with commit f5409d94. With a small correction to the change, this should now function as expected. The `status-brobe.sh` script checks the value for `GLUSTER_BLOCK_ENABLED` and compares it to `1`. However the `update-params.sh` script set the variable by default to `TRUE`. gluster-kubernetes and openshift-ansible both set the variable to `"1"` by default, so should `update-params.sh`.

Updates: #120

2019-01-15 11:51 UTC, SaravanaStorageNetwork commented
@nixpanic  But status-probe refers the variable GLUSTER_BLOCKD_STATUS_PROBE_ENABLE( which is for whether to check gluster blockd status or not)   
Here, it is GLUSTER_BLOCK_ENABLED which is for whether enable/disable GLUSTER_BLOCK ?

Note: 
It is good idea to merge them both, but currently  they are different variables(with different meaning).

2019-01-15 12:02 UTC, nixpanic commented
On Tue, Jan 15, 2019 at 03:51:06AM -0800, Saravanakumar Arumugam wrote:
> @nixpanic  But status-probe refers the variable GLUSTER_BLOCKD_STATUS_PROBE_ENABLE( which is for whether to check gluster blockd status or not)   
> Here, it is GLUSTER_BLOCK_ENABLED which is for whether enable/disable GLUSTER_BLOCK ?
> 
> Note: 
> It is good idea to merge them both, but currently  they are different variables(with different meaning).

Ah, right! I'll rename them and only keep the one we have in
gluster-kubernetes and openshift-ansible.

2019-01-16 07:41 UTC, nixpanic commented
I have modified the `probe-status.sh` script to **also** check the `GLUSTER_BLOCK_ENABLED` variable now. By default gluster-block is enabled, and so is the probe. `GLUSTER_BLOCKD_STATUS_PROBE_ENABLE` can still be used to disable the probe, there could be users that have configured it that way.

2019-01-16 14:51 UTC, phlogistonjohn approved these changes
Looks reasonable enough to me.

2019-01-17 10:37 UTC, SaravanaStorageNetwork requested changes

2019-01-17 10:37 UTC, SaravanaStorageNetwork commented on CentOS/update-params.sh
> +if [ "$GLUSTER_BLOCK_ENABLED" == 1 ]; then
Here, 1 is numeric value => eq is better.

2019-01-17 10:37 UTC, SaravanaStorageNetwork commented on CentOS/update-params.sh
> +        systemctl enable gluster-blockd.service
Is the actual issue mentioned here issue #120  resolved here? Please reboot the node and see whether this specific line executes fine.

2019-01-17 10:40 UTC, SaravanaStorageNetwork commented on CentOS/update-params.sh
> +if [ "$GLUSTER_BLOCK_ENABLED" == 1 ]; then
> < This change was recently reverted with commit f5409d9. With a small correction to the change, this should now function as expected. The status-probe.sh script checks the value for GLUSTER_BLOCK_ENABLED and compares it to 1. However the update-params.sh script set the variable by default to TRUE. gluster-kubernetes and openshift-ansible both set the variable to "1" by default, so should update-params.sh.

This needs an update too

2026-02-09 07:41 UTC, nixpanic commented
Closing as stale.

2026-02-09 07:41 UTC, closed without merging