[Fedora] Remove extra systemd services from the container
gluster/gluster-containers pull request #193
Opened 2022-08-04 11:06 UTC by black-dragon74

Signed-off-by: black-dragon74 <nickk.2974@gmail.com>

2022-08-09 08:47 UTC, nixpanic requested changes

2022-08-09 08:47 UTC, nixpanic commented on Fedora/Dockerfile
> +    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
deleting files from `/lib` is really not clean, better to disabled these with a systemctl command as done further below.

2022-08-09 08:49 UTC, black-dragon74 commented on Fedora/Dockerfile
> +    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
I guess I should apply the same to `CentOS` container then?

2022-08-09 08:54 UTC, nixpanic commented on Fedora/Dockerfile
> +    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
yes, that would be the cleanest

2022-08-09 09:35 UTC, black-dragon74 commented on Fedora/Dockerfile
> +    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
It makes sense to close this PR. The same issue is rectified for CentOS container at #196 

Regards

2022-08-16 05:31 UTC, black-dragon74 commented on Fedora/Dockerfile
> +    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
@nixpanic It is a standard practice wherever systemd is used inside docker to run these commands to stop extra services from running. One such example is [here](https://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container).

I think it is safe to merge this and scratch #196 

Regards

2022-08-16 07:36 UTC, nixpanic approved these changes

2022-08-16 07:36 UTC, nixpanic commented on Fedora/Dockerfile
> +    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
I'm still not very fond of removing files from an installed RPM. It is bad practise in almost all environments, except for container-images. Disabling/masking the services with the `systemctl` command would be much cleaner, and sticks with the same prpcess that should be applied on other environments.

That said, container-images are an exception... So, it is not a blocking issue, just something that could be done cleaner.

2022-08-19 04:49 UTC, merged