[centos] Use latest version of Glusterfs
gluster/gluster-containers pull request #194
Opened 2022-08-08 03:23 UTC by black-dragon74

Signed-off-by: black-dragon74 <nickk.2974@gmail.com>

2022-08-09 08:49 UTC, nixpanic requested changes

2022-08-09 08:49 UTC, nixpanic commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
installing from CentOS 7 on CentOS 9? there should be a gperftools package for CentOS 9 somewhere too

2022-08-09 08:51 UTC, black-dragon74 commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
Actually there isn't. It's not there even for CentOS 8. As this is related to tcmalloc, using older version is fine as we don't have any changes that might break stuff in the core gluster project.

2022-08-09 08:55 UTC, nixpanic commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
what requires this then? do you have some installation or runtime error about it?

2022-08-09 08:56 UTC, black-dragon74 commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
Give me some time, I'll get it for you. It's tcmalloc IIRC, will confirm though.

2022-08-09 09:16 UTC, nixpanic commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
Packages that are missing should get included in the CentOS Storage SIG repositories, if they are required for some Gluster components, that is. Installing them from somewhere else than standard repositories is always wrong.

2022-08-09 09:18 UTC, black-dragon74 commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
```
nothing provides libtcmalloc_minimal.so.4()(64bit) needed by glusterfs-server-10.2-1.el9s.x86_64
```

It is `libtcmalloc`

Regards

2022-08-09 09:19 UTC, black-dragon74 commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
> Packages that are missing should get included in the CentOS Storage SIG repositories

Could you please look into this? `gperftools-libs` needs to be added. Would be also nice to have it available on CentOS 8.

Regards

2022-08-09 14:23 UTC, nixpanic commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
the package is tagged and should land on http://mirror.stream.centos.org/SIGs/9-stream/storage/x86_64/gluster-10/Packages/g/ soon now too.

2022-08-16 05:55 UTC, black-dragon74 commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
We need `libunwind` too as `gperftools-libs` require it. Can you please tag it? Ref [here](https://centos.pkgs.org/8/epel-x86_64/libunwind-1.3.1-3.el8.x86_64.rpm.html).

Regards

2022-08-16 07:42 UTC, nixpanic commented on CentOS/Dockerfile
> +yum --setopt=tsflags=nodocs -y install http://mirror.centos.org/centos/7/os/x86_64/Packages/gperftools-libs-2.6.1-1.el7.x86_64.rpm  && \
The package comes from the CentOS Community Build System, at https://cbs.centos.org/koji/buildinfo?buildID=34022

This has now been added to the storage9s-gluster-10-release repository, so it should land on the mirrors soon.

2022-08-16 08:42 UTC, black-dragon74 commented
/test

2022-08-16 08:58 UTC, nixpanic approved these changes

2022-08-16 10:12 UTC, merged

2022-08-16 10:13 UTC, humblec approved these changes