[centos] Group similar build steps into a single layer
gluster/gluster-containers pull request #195
Opened 2022-08-08 04:38 UTC by black-dragon74

Multiple `ADD` statements created separate layers for each call. Group them all in a single layer.

Signed-off-by: black-dragon74 <nickk.2974@gmail.com>

2022-08-09 08:53 UTC, nixpanic requested changes

2022-08-09 08:53 UTC, nixpanic commented on CentOS/Dockerfile
> +WORKDIR /tmp
no need to change the workdir, just do:

```
COPY . /tmp/container-setup/
RUN true \
    && cd /tmp/container-setup \
    && ./setup-services.sh
    && cd -
    && rm -rf /tmp/container-setup \
    && true
```
cleaning up the files from the temporary directory would be nice.

2022-08-09 08:55 UTC, black-dragon74 commented on CentOS/Dockerfile
> +WORKDIR /tmp
Will do. For my knowledge, why do we mask calls between `true`? Does it serve any purpose?

2022-08-09 09:21 UTC, nixpanic commented on CentOS/Dockerfile
> +WORKDIR /tmp
not 'mask', but executing multiple commands under a single `RUN` statement.

The `true` at the start and end make it possible to use `git blame` when commands inside the `RUN` get modified later on. Not sure where I got the recommendation from, but it works well for me.

2022-08-09 09:25 UTC, black-dragon74 commented on CentOS/Dockerfile
> +WORKDIR /tmp
From [here](https://github.com/projectatomic/container-best-practices/blob/master/creating/creating_index.adoc), 
```
Editing a line with a command that that you don’t want to change 
presents a risk of introducing a bug, and you also obscure the line’s history. 
This can be mitigated by having both the first and last commands true - they don’t do anything.
```

Now I understand it better. Always confused me.

2022-08-16 07:44 UTC, nixpanic approved these changes

2022-08-16 11:11 UTC, merged